# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ ["QT_QPA_PLATFORM_PLUGIN_PATH"] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 703)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 20, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_in4 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_in4.setGeometry(QtCore.QRect(170, 110, 711, 151))
        self.txt_in4.setObjectName("txt_in4")
        self.btn_ge = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ge.setGeometry(QtCore.QRect(460, 540, 91, 41))
        self.btn_ge.setObjectName("btn_ge")
        self.btn_verify_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify_2.setGeometry(QtCore.QRect(730, 540, 91, 41))
        self.btn_verify_2.setObjectName("btn_verify_2")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(190, 540, 91, 41))
        self.btn_sign.setObjectName("btn_sign")
        self.txt_sign = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(170, 310, 711, 151))
        self.txt_sign.setObjectName("txt_sign")
        self.lbl_in4 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_in4.setGeometry(QtCore.QRect(40, 120, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_in4.setFont(font)
        self.lbl_in4.setObjectName("lbl_in4")
        self.lbl_sign = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sign.setGeometry(QtCore.QRect(40, 310, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_sign.setFont(font)
        self.lbl_sign.setObjectName("lbl_sign")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 970, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ECC CIPHER"))
        self.btn_ge.setText(_translate("MainWindow", "Generate Key"))
        self.btn_verify_2.setText(_translate("MainWindow", "Verify"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.lbl_in4.setText(_translate("MainWindow", "Information"))
        self.lbl_sign.setText(_translate("MainWindow", "Signature"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
