# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ["QI_QPA_PLATFORM_PLUGIN_PATH"] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 684)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_cipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipherText.setGeometry(QtCore.QRect(120, 280, 381, 151))
        self.txt_cipherText.setObjectName("txt_cipherText")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 0, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_ge = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ge.setGeometry(QtCore.QRect(120, 530, 91, 41))
        self.btn_ge.setObjectName("btn_ge")
        self.txt_plainText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plainText.setGeometry(QtCore.QRect(120, 80, 381, 151))
        self.txt_plainText.setObjectName("txt_plainText")
        self.lbl_cipherText = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cipherText.setGeometry(QtCore.QRect(0, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_cipherText.setFont(font)
        self.lbl_cipherText.setObjectName("lbl_cipherText")
        self.lbl_plain = QtWidgets.QLabel(self.centralwidget)
        self.lbl_plain.setGeometry(QtCore.QRect(10, 90, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_plain.setFont(font)
        self.lbl_plain.setObjectName("lbl_plain")
        self.btn_en = QtWidgets.QPushButton(self.centralwidget)
        self.btn_en.setGeometry(QtCore.QRect(300, 530, 91, 41))
        self.btn_en.setObjectName("btn_en")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(740, 530, 91, 41))
        self.btn_sign.setObjectName("btn_sign")
        self.lbl_in4 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_in4.setGeometry(QtCore.QRect(580, 80, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_in4.setFont(font)
        self.lbl_in4.setObjectName("lbl_in4")
        self.txt_in4 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_in4.setGeometry(QtCore.QRect(670, 80, 381, 151))
        self.txt_in4.setObjectName("txt_in4")
        self.txt_sign = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(670, 280, 381, 151))
        self.txt_sign.setObjectName("txt_sign")
        self.btn_verify_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify_2.setGeometry(QtCore.QRect(960, 530, 91, 41))
        self.btn_verify_2.setObjectName("btn_verify_2")
        self.btn_de = QtWidgets.QPushButton(self.centralwidget)
        self.btn_de.setGeometry(QtCore.QRect(520, 530, 91, 41))
        self.btn_de.setObjectName("btn_de")
        self.lbl_sign = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sign.setGeometry(QtCore.QRect(580, 280, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_sign.setFont(font)
        self.lbl_sign.setObjectName("lbl_sign")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.btn_ge.setText(_translate("MainWindow", "Generate Key"))
        self.lbl_cipherText.setText(_translate("MainWindow", "Cipher Text:"))
        self.lbl_plain.setText(_translate("MainWindow", "Plain Text:"))
        self.btn_en.setText(_translate("MainWindow", "Encrypt"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.lbl_in4.setText(_translate("MainWindow", "Information"))
        self.btn_verify_2.setText(_translate("MainWindow", "Verify"))
        self.btn_de.setText(_translate("MainWindow", "Decrypt"))
        self.lbl_sign.setText(_translate("MainWindow", "Signature"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
